package com.myspace.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class jartest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String dog;

	public jartest() {
	}

	public java.lang.String getDog() {
		return this.dog;
	}

	public void setDog(java.lang.String dog) {
		this.dog = dog;
	}

	public jartest(java.lang.String dog) {
		this.dog = dog;
	}

}