package com.myspace.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testhook2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date test;

	public testhook2() {
	}

	public java.util.Date getTest() {
		return this.test;
	}

	public void setTest(java.util.Date test) {
		this.test = test;
	}

	public testhook2(java.util.Date test) {
		this.test = test;
	}

}