package com.myspace.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testgithookjar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String car;

	public testgithookjar() {
	}

	public java.lang.String getCar() {
		return this.car;
	}

	public void setCar(java.lang.String car) {
		this.car = car;
	}

	public testgithookjar(java.lang.String car) {
		this.car = car;
	}

}