package com.myspace.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testbranch implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean branch;

	public testbranch() {
	}

	public java.lang.Boolean getBranch() {
		return this.branch;
	}

	public void setBranch(java.lang.Boolean branch) {
		this.branch = branch;
	}

	public testbranch(java.lang.Boolean branch) {
		this.branch = branch;
	}

}