package com.myspace.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testhook1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer carforhook;

	public testhook1() {
	}

	public java.lang.Integer getCarforhook() {
		return this.carforhook;
	}

	public void setCarforhook(java.lang.Integer carforhook) {
		this.carforhook = carforhook;
	}

	public testhook1(java.lang.Integer carforhook) {
		this.carforhook = carforhook;
	}

}