package com.myspace.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testgithookjar implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public testgithookjar() {
    }




}